import 'package:cloud_firestore/cloud_firestore.dart';

/// Service for generating auto-incrementing IDs with school short code prefix
/// Format: {SCHOOL_SHORT_CODE}_{TYPE}_{NUMBER}
/// Examples: ES360_STF_001, ES360_LV_001
class IdGeneratorService {
  final FirebaseFirestore _firestore;

  IdGeneratorService(this._firestore);

  /// Generate next staff employee ID
  /// Format: {shortCode}{paddedNumber}
  /// Example: ES360001
  Future<String> generateStaffId(String schoolId) async {
    print('🔢 [ID_GENERATOR] Generating staff ID for school: $schoolId');
    try {
      final result = await _generateId(schoolId, 'staffCounter', '');
      print('✅ [ID_GENERATOR] Generated staff ID: $result');
      return result;
    } catch (e, stackTrace) {
      print('❌ [ID_GENERATOR] Error generating staff ID: $e');
      print('❌ [ID_GENERATOR] Error type: ${e.runtimeType}');
      print('❌ [ID_GENERATOR] Stack trace: $stackTrace');
      rethrow;
    }
  }

  /// Generate leave application ID using Firestore auto-generated ID
  /// Format: LV_{autoGeneratedId}
  /// Example: LV_abc123xyz
  Future<String> generateLeaveId(String schoolId) async {
    final docRef = _firestore.collection('schools').doc(schoolId).collection('leaves').doc();
    return 'LV_${docRef.id}';
  }

  /// Generate permission request ID using Firestore auto-generated ID
  /// Format: PM_{autoGeneratedId}
  /// Example: PM_abc123xyz
  Future<String> generatePermissionId(String schoolId) async {
    final docRef = _firestore.collection('schools').doc(schoolId).collection('permissions').doc();
    return 'PM_${docRef.id}';
  }

  /// Internal method to generate ID using Firestore transaction
  Future<String> _generateId(String schoolId, String counterField, String typePrefix) async {
    print('🔢 [ID_GENERATOR] Starting ID generation for field: $counterField');
    final schoolRef = _firestore.collection('schools').doc(schoolId);
    final counterRef = _firestore.collection('schoolCounters').doc(schoolId);
    
    try {
      // Get school data for short code
      print('🔢 [ID_GENERATOR] Fetching school document...');
      final schoolDoc = await schoolRef.get();
      
      if (!schoolDoc.exists) {
        throw Exception('School not found');
      }
      
      final data = schoolDoc.data()!;
      final schoolName = (data['name'] as String?) ?? (data['schoolName'] as String?) ?? '';
      final shortCode = (data['shortCode'] as String?) ?? _generateShortCode(schoolName);
      print('🔢 [ID_GENERATOR] School short code: $shortCode');
      
      // Get or create counter document (without transaction for web compatibility)
      print('🔢 [ID_GENERATOR] Fetching counter document...');
      final counterDoc = await counterRef.get();
      
      final currentCounter = counterDoc.exists 
          ? (counterDoc.data()![counterField] as int?) ?? 0 
          : 0;
      final nextCounter = currentCounter + 1;
      print('🔢 [ID_GENERATOR] Current counter: $currentCounter, Next counter: $nextCounter');
      
      // Update counter
      print('🔢 [ID_GENERATOR] Updating counter document...');
      if (counterDoc.exists) {
        await counterRef.update({
          counterField: nextCounter,
          'updatedAt': FieldValue.serverTimestamp(),
        });
      } else {
        await counterRef.set({
          counterField: nextCounter,
          'schoolId': schoolId,
          'updatedAt': FieldValue.serverTimestamp(),
        });
      }
      print('✅ [ID_GENERATOR] Counter updated successfully');
      
      // Generate ID with padded number (3 digits minimum)
      final paddedNumber = nextCounter.toString().padLeft(3, '0');
      if (typePrefix.isEmpty) {
        // For staff IDs: schoolcode + number (e.g., ES360001)
        return '$shortCode$paddedNumber';
      }
      return '${shortCode}_${typePrefix}_$paddedNumber';
    } catch (e, stackTrace) {
      print('❌ [ID_GENERATOR] Transaction error: $e');
      print('❌ [ID_GENERATOR] Error type: ${e.runtimeType}');
      print('❌ [ID_GENERATOR] Stack trace: $stackTrace');
      rethrow;
    }
  }

  /// Generate short code from school name
  static String _generateShortCode(String schoolName) {
    if (schoolName.isEmpty) return 'SCH';
    final words = schoolName.toUpperCase().split(' ').where((w) => w.isNotEmpty).toList();
    if (words.length >= 2) {
      return '${words[0][0]}${words[1][0]}${words.length > 2 ? words[2][0] : ''}';
    }
    return schoolName.substring(0, schoolName.length >= 3 ? 3 : schoolName.length).toUpperCase();
  }

  /// Initialize counters for a school if they don't exist
  Future<void> initializeCounters(String schoolId, String schoolName) async {
    final schoolRef = _firestore.collection('schools').doc(schoolId);
    final counterRef = _firestore.collection('schoolCounters').doc(schoolId);
    
    final schoolDoc = await schoolRef.get();
    if (!schoolDoc.exists) return;
    
    final data = schoolDoc.data()!;
    final schoolUpdates = <String, dynamic>{};
    
    // Only update school document with shortCode if needed
    if (data['shortCode'] == null) {
      schoolUpdates['shortCode'] = _generateShortCode(schoolName);
    }
    
    if (schoolUpdates.isNotEmpty) {
      schoolUpdates['updatedAt'] = FieldValue.serverTimestamp();
      await schoolRef.update(schoolUpdates);
    }
    
    // Initialize counters in separate collection
    final counterDoc = await counterRef.get();
    if (!counterDoc.exists) {
      await counterRef.set({
        'schoolId': schoolId,
        'staffCounter': 0,
        'leaveCounter': 0,
        'permissionCounter': 0,
        'updatedAt': FieldValue.serverTimestamp(),
      });
    }
  }
}
