import '../../domain/entities/fee_structure_v2.dart';
import '../../domain/entities/fee_term.dart';
import '../../domain/entities/fee_payment.dart';
import '../../domain/entities/student.dart';
import '../../domain/entities/academic_year.dart';

/// Helper that maps a FeeStructureV2 (with multiple terms) to the legacy
/// FeePayment component fields used by the existing payment flow.
///
/// The existing flow stores a single payment record with component fields
/// (admissionFeePaid, tuitionFeePaid, examFeePaid, vanFeePaid, arrearsPaid)
/// and a totalAmount. To stay compatible, we map each term to a component
/// based on the term's name and the structure type.
///
/// Example mappings (customizable per school):
///   - YEARLY → tuitionFeePaid = annual amount
///   - MONTHLY → tuitionFeePaid = monthly amount (per month)
///   - TERM_WISE → tuitionFeePaid = term amount
///   - CUSTOM → tuitionFeePaid = installment amount
///
/// If a term name contains 'Admission' → admissionFeePaid,
/// 'Exam' → examFeePaid, 'Van' → vanFeePaid, otherwise the default is tuitionFeePaid.
class FeeStructureToPaymentMapper {
  /// Returns a map of component field names to amounts for a given term.
  /// Useful for UI pre-fill or Excel row generation.
  ///
  /// If [FeeTerm.category] is explicitly set, that wins. Otherwise the term
  /// name is inspected for backward compatibility with structures created
  /// before the category field existed.
  ///
  /// The returned key is one of:
  ///   - `admissionFeePaid`, `tuitionFeePaid`, `examFeePaid`, `vanFeePaid`
  ///     (for the four standard categories that map to dedicated FeePayment
  ///     fields), OR
  ///   - the UPPER_CASE category code itself (e.g. `SPORTS_FEE`) for custom
  ///     categories — these are stored in
  ///     [FeePayment.customCategoryAmounts].
  static Map<String, double> mapTermToComponents(FeeTerm term) {
    final cat = term.category.toUpperCase().trim();
    switch (cat) {
      case 'ADMISSION':
        return {'admissionFeePaid': term.amount};
      case 'TUITION':
        return {'tuitionFeePaid': term.amount};
      case 'EXAM':
        return {'examFeePaid': term.amount};
      case 'VAN':
        return {'vanFeePaid': term.amount};
      case '':
        // No category set — fall back to legacy name inference.
        return _inferFromName(term);
      default:
        // Custom category (e.g. SPORTS_FEE).
        return {cat: term.amount};
    }
  }

  /// Legacy name-based inference, retained for terms saved before the
  /// `category` field existed.
  static Map<String, double> _inferFromName(FeeTerm term) {
    final name = term.termName.toLowerCase();
    if (name.contains('admission')) return {'admissionFeePaid': term.amount};
    if (name.contains('exam')) return {'examFeePaid': term.amount};
    if (name.contains('van')) return {'vanFeePaid': term.amount};
    return {'tuitionFeePaid': term.amount};
  }

  /// Creates a FeePayment record for a specific term of a structure.
  /// The record will have only one component populated (based on term name).
  /// The caller can sum multiple payments across terms if needed.
  static FeePayment createPaymentForTerm({
    required FeeStructureV2 structure,
    required FeeTerm term,
    required Student student,
    required PaymentMode paymentMode,
    required String cashierName,
    String? remarks,
  }) {
    final components = mapTermToComponents(term);
    final admission = components['admissionFeePaid'] ?? 0.0;
    final tuition = components['tuitionFeePaid'] ?? 0.0;
    final exam = components['examFeePaid'] ?? 0.0;
    final van = components['vanFeePaid'] ?? 0.0;

    return FeePayment(
      id: '', // will be set by repository
      schoolId: structure.schoolId,
      billId: 0, // will be generated by repository
      studentId: student.id,
      studentName: student.name,
      className: student.className,
      section: student.section,
      academicYear: structure.academicYear,
      fiscalYear: FiscalYear.getCurrentYearCode(),
      admissionFeePaid: admission,
      tuitionFeePaid: tuition,
      examFeePaid: exam,
      vanFeePaid: van,
      arrearsPaid: 0.0,
      totalAmount: term.amount,
      paymentMode: paymentMode,
      remarks: remarks,
      cashierName: cashierName,
      paymentDate: DateTime.now(),
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      createdBy: cashierName, // optional; could be userId
    );
  }

  /// Generates a list of FeePayment rows (one per term) for a given student
  /// and structure. Useful when bulk‑creating payment rows for Excel upload.
  static List<FeePayment> generatePaymentsForStudent({
    required FeeStructureV2 structure,
    required Student student,
    required PaymentMode paymentMode,
    required String cashierName,
    String? remarks,
  }) {
    return structure.terms.map((term) {
      return createPaymentForTerm(
        structure: structure,
        term: term,
        student: student,
        paymentMode: paymentMode,
        cashierName: cashierName,
        remarks: remarks,
      );
    }).toList();
  }

  /// Computes the total amount due for a structure (sum of all terms).
  static double totalAmountForStructure(FeeStructureV2 structure) {
    return structure.terms.fold(0.0, (sum, term) => sum + term.amount);
  }

  /// Computes the amount due for a specific term.
  static double totalAmountForTerm(FeeTerm term) => term.amount;

  /// Returns the due date for a term (already stored in FeeTerm).
  static DateTime dueDateForTerm(FeeTerm term) => term.dueDate;

  /// Returns a readable label for a term (e.g., “June (Monthly)” or “Term 1”).
  static String termLabel(FeeTerm term, FeeStructureType type) {
    switch (type) {
      case FeeStructureType.MONTHLY:
        return term.termName; // month name already
      case FeeStructureType.TERM_WISE:
        return term.termName;
      case FeeStructureType.YEARLY:
        return 'Annual';
      case FeeStructureType.CUSTOM:
        return term.termName;
    }
  }
}
