// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQab7Eg9pWGckqURofTuGSssJRGb2qCfc',
    appId: '1:937918362792:web:96ee224f624e8b67f73e9d',
    messagingSenderId: '937918362792',
    projectId: 'eazy-school-360',
    authDomain: 'eazy-school-360.firebaseapp.com',
    storageBucket: 'eazy-school-360.appspot.com',
    measurementId: 'G-DFLZ5MM7Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQab7Eg9pWGckqURofTuGSssJRGb2qCfc',
    appId: '1:937918362792:android:96ee224f624e8b67f73e9d',
    messagingSenderId: '937918362792',
    projectId: 'eazy-school-360',
    storageBucket: 'eazy-school-360.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQab7Eg9pWGckqURofTuGSssJRGb2qCfc',
    appId: '1:937918362792:ios:96ee224f624e8b67f73e9d',
    messagingSenderId: '937918362792',
    projectId: 'eazy-school-360',
    storageBucket: 'eazy-school-360.appspot.com',
    iosClientId: '937918362792-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com',
    iosBundleId: 'com.example.eazySchool360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQab7Eg9pWGckqURofTuGSssJRGb2qCfc',
    appId: '1:937918362792:ios:96ee224f624e8b67f73e9d',
    messagingSenderId: '937918362792',
    projectId: 'eazy-school-360',
    storageBucket: 'eazy-school-360.appspot.com',
    iosClientId: '937918362792-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com',
    iosBundleId: 'com.example.eazySchool360',
  );
}
