// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps - DEV ENVIRONMENT.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS1-6InT-DAROMIOPi4unigPW6F12_-Xc',
    appId: '1:740019858942:web:106b106e947209046f24af',
    messagingSenderId: '740019858942',
    projectId: 'eazyschool-360-dev',
    authDomain: 'eazyschool-360-dev.firebaseapp.com',
    storageBucket: 'eazyschool-360-dev.firebasestorage.app',
    measurementId: 'G-0E0WNWBBTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS1-6InT-DAROMIOPi4unigPW6F12_-Xc',
    appId: '1:740019858942:android:YOUR_ANDROID_APP_ID', // TODO: Add Android app ID
    messagingSenderId: '740019858942',
    projectId: 'eazyschool-360-dev',
    storageBucket: 'eazyschool-360-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS1-6InT-DAROMIOPi4unigPW6F12_-Xc',
    appId: '1:740019858942:ios:YOUR_IOS_APP_ID', // TODO: Add iOS app ID
    messagingSenderId: '740019858942',
    projectId: 'eazyschool-360-dev',
    storageBucket: 'eazyschool-360-dev.firebasestorage.app',
    iosBundleId: 'com.eazyschool360.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS1-6InT-DAROMIOPi4unigPW6F12_-Xc',
    appId: '1:740019858942:ios:YOUR_MACOS_APP_ID', // TODO: Add macOS app ID
    messagingSenderId: '740019858942',
    projectId: 'eazyschool-360-dev',
    storageBucket: 'eazyschool-360-dev.firebasestorage.app',
    iosBundleId: 'com.eazyschool360.dev',
  );
}
