// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps - PRODUCTION ENVIRONMENT.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ2r7x8m9n0p1q2r3s4t5u6v7w8x9y0z', // TODO: Replace with actual production API key
    appId: '1:937918362792:web:YOUR_PROD_APP_ID', // TODO: Replace with actual app ID
    messagingSenderId: '937918362792',
    projectId: 'eazy-school-360',
    authDomain: 'eazy-school-360.firebaseapp.com',
    storageBucket: 'eazy-school-360.firebasestorage.app',
    measurementId: 'G-YOUR_MEASUREMENT_ID', // TODO: Replace
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_PROD_API_KEY',
    appId: 'YOUR_PROD_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_PROD_SENDER_ID',
    projectId: 'eazy-school-360',
    storageBucket: 'eazy-school-360.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_PROD_API_KEY',
    appId: 'YOUR_PROD_IOS_APP_ID',
    messagingSenderId: 'YOUR_PROD_SENDER_ID',
    projectId: 'eazy-school-360',
    storageBucket: 'eazy-school-360.firebasestorage.app',
    iosBundleId: 'com.eazyschool360.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_PROD_API_KEY',
    appId: 'YOUR_PROD_MACOS_APP_ID',
    messagingSenderId: 'YOUR_PROD_SENDER_ID',
    projectId: 'eazy-school-360',
    storageBucket: 'eazy-school-360.firebasestorage.app',
    iosBundleId: 'com.eazyschool360.app',
  );
}
