// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps - TEST ENVIRONMENT.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_TEST_API_KEY', // TODO: Replace with test project API key
    appId: 'YOUR_TEST_APP_ID', // TODO: Replace with test project app ID
    messagingSenderId: 'YOUR_TEST_SENDER_ID', // TODO: Replace
    projectId: 'eazyschool-360-test', // TODO: Create test project
    authDomain: 'eazyschool-360-test.firebaseapp.com',
    storageBucket: 'eazyschool-360-test.firebasestorage.app',
    measurementId: 'YOUR_TEST_MEASUREMENT_ID', // TODO: Replace
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_TEST_API_KEY',
    appId: 'YOUR_TEST_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_TEST_SENDER_ID',
    projectId: 'eazyschool-360-test',
    storageBucket: 'eazyschool-360-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_TEST_API_KEY',
    appId: 'YOUR_TEST_IOS_APP_ID',
    messagingSenderId: 'YOUR_TEST_SENDER_ID',
    projectId: 'eazyschool-360-test',
    storageBucket: 'eazyschool-360-test.firebasestorage.app',
    iosBundleId: 'com.eazyschool360.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_TEST_API_KEY',
    appId: 'YOUR_TEST_MACOS_APP_ID',
    messagingSenderId: 'YOUR_TEST_SENDER_ID',
    projectId: 'eazyschool-360-test',
    storageBucket: 'eazyschool-360-test.firebasestorage.app',
    iosBundleId: 'com.eazyschool360.test',
  );
}
